# Generated by Django 5.1.4 on 2024-12-22 10:45

import django.db.models.deletion
import treatment_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן ב')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('name', models.CharField(max_length=100, verbose_name='שם')),
                ('birth_date', models.DateField(verbose_name='תאריך לידה')),
                ('school', models.CharField(max_length=100, verbose_name='בית ספר')),
                ('grade', models.CharField(max_length=20, verbose_name='כיתה')),
                ('medical_info', models.TextField(blank=True, null=True, verbose_name='מידע רפואי')),
                ('special_needs', models.TextField(blank=True, null=True, verbose_name='צרכים מיוחדים')),
            ],
            options={
                'verbose_name': 'ילד',
                'verbose_name_plural': 'ילדים',
                'ordering': ['family', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן ב')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('family_name', models.CharField(max_length=100, verbose_name='שם משפחה')),
                ('family_status', models.CharField(choices=[('married', 'נשואים'), ('divorced', 'גרושים'), ('single_father', 'אב יחיד'), ('single_mother', 'אם יחידה'), ('other', 'אחר')], default='married', max_length=20, verbose_name='סטטוס משפחתי')),
                ('address', models.TextField(verbose_name='כתובת')),
                ('phone_number', models.CharField(max_length=20, verbose_name='טלפון ראשי')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='שם האב')),
                ('father_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='טלפון האב')),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='אימייל האב')),
                ('father_id', models.CharField(blank=True, max_length=9, null=True, verbose_name='תעודת זהות האב')),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='שם האם')),
                ('mother_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='טלפון האם')),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='אימייל האם')),
                ('mother_id', models.CharField(blank=True, max_length=9, null=True, verbose_name='תעודת זהות האם')),
            ],
            options={
                'verbose_name': 'משפחה',
                'verbose_name_plural': 'משפחות',
                'ordering': ['family_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן ב')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('name', models.CharField(max_length=200, verbose_name='שם המסמך')),
                ('document_type', models.CharField(choices=[('consent', 'טופס הסכמה'), ('treatment', 'טופס טיפול'), ('medical', 'מסמך רפואי'), ('educational', 'מסמך חינוכי'), ('other', 'אחר')], default='other', max_length=20, verbose_name='סוג מסמך')),
                ('file', models.FileField(upload_to='documents/', validators=[treatment_app.models.validate_file_extension], verbose_name='קובץ')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='treatment_app.child', verbose_name='ילד')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='treatment_app.family', verbose_name='משפחה')),
            ],
            options={
                'verbose_name': 'מסמך',
                'verbose_name_plural': 'מסמכים',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='treatment_app.family', verbose_name='משפחה'),
        ),
    ]
