# Generated by Django 5.1.4 on 2024-12-22 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='treatment_app.child'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('medical', 'מסמך רפואי'), ('educational', 'מסמך חינוכי'), ('psychological', 'מסמך פסיכולוגי'), ('financial', 'מסמך פיננסי'), ('other', 'אחר')], max_length=20, verbose_name='סוג המסמך'),
        ),
        migrations.AlterField(
            model_name='document',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='treatment_app.family'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255, verbose_name='שם המסמך'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='עודכן בתאריך'),
        ),
    ]
