# Generated by Django 5.1.4 on 2024-12-22 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='טלפון')),
                ('specialization', models.CharField(max_length=100, verbose_name='התמחות')),
                ('active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'מטפל',
                'verbose_name_plural': 'מטפלים',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='assigned_therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_families', to='treatment_app.therapist', verbose_name='מטפל מוקצה'),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן ב')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('date', models.DateTimeField(verbose_name='תאריך ושעה')),
                ('status', models.CharField(choices=[('scheduled', 'מתוכנן'), ('in_progress', 'בטיפול'), ('completed', 'הושלם'), ('cancelled', 'בוטל')], default='scheduled', max_length=20, verbose_name='סטטוס')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='סיכום טיפול')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='treatment_app.child', verbose_name='ילד')),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='treatment_app.therapist', verbose_name='מטפל')),
            ],
            options={
                'verbose_name': 'טיפול',
                'verbose_name_plural': 'טיפולים',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='treatment_app.treatment', verbose_name='טיפול קשור'),
        ),
    ]
