# Generated by Django 5.1.4 on 2024-12-22 13:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_app', '0004_family_parents_type_treatment_family_treatment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name'], 'verbose_name': 'משפחה', 'verbose_name_plural': 'משפחות'},
        ),
        migrations.AlterField(
            model_name='family',
            name='confidentiality_waiver',
            field=models.FileField(blank=True, null=True, upload_to='confidentiality_waivers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='טופס ויתור סודיות'),
        ),
        migrations.AlterField(
            model_name='family',
            name='consent_form',
            field=models.FileField(blank=True, null=True, upload_to='consent_forms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='טופס הסכמה'),
        ),
        migrations.AlterField(
            model_name='family',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to=settings.AUTH_USER_MODEL, verbose_name='מטפל'),
        ),
    ]
