# Generated by Django 5.1.4 on 2024-12-22 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_app', '0006_therapistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='אלרגיות'),
        ),
        migrations.AddField(
            model_name='child',
            name='medications',
            field=models.TextField(blank=True, verbose_name='תרופות'),
        ),
        migrations.AddField(
            model_name='child',
            name='school_counselor_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='שם היועץ/ת'),
        ),
        migrations.AddField(
            model_name='child',
            name='school_counselor_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='טלפון היועץ/ת'),
        ),
        migrations.AddField(
            model_name='child',
            name='special_needs',
            field=models.TextField(blank=True, verbose_name='צרכים מיוחדים'),
        ),
        migrations.AddField(
            model_name='child',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='שם המורה'),
        ),
        migrations.AddField(
            model_name='child',
            name='teacher_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='טלפון המורה'),
        ),
        migrations.AddField(
            model_name='child',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment_app.therapistprofile', verbose_name='מטפל'),
        ),
    ]
