# Generated by Django 5.1.4 on 2024-12-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_app', '0008_alter_treatment_options_remove_treatment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='actual_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך בפועל'),
        ),
    ]
