# Generated by Django 5.1.4 on 2024-12-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_app', '0010_family_family_status_family_father_consent_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='primary_contact',
            field=models.BooleanField(default=False, verbose_name='האם קיים איש קשר עיקרי'),
        ),
        migrations.AddField(
            model_name='family',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='שם איש קשר עיקרי'),
        ),
        migrations.AddField(
            model_name='family',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='טלפון איש קשר עיקרי'),
        ),
    ]
