# Generated by Django 5.1.4 on 2024-12-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_app', '0011_family_primary_contact_family_primary_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='family',
            name='primary_contact_name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='primary_contact_phone',
        ),
        migrations.AddField(
            model_name='family',
            name='primary_contact_type',
            field=models.CharField(blank=True, choices=[('father', 'אב המשפחה'), ('mother', 'אם המשפחה'), ('other', 'אחר')], max_length=10, null=True, verbose_name='סוג איש קשר עיקרי'),
        ),
    ]
