# Generated by Django 5.1.4 on 2024-12-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_app', '0013_socialworker_alter_family_family_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='father_consent_form',
            field=models.FileField(blank=True, null=True, upload_to='consent_forms/father/', verbose_name='טופס הסכמה אב'),
        ),
        migrations.AlterField(
            model_name='family',
            name='mother_consent_form',
            field=models.FileField(blank=True, null=True, upload_to='consent_forms/mother/', verbose_name='טופס הסכמה אם'),
        ),
    ]
